obj-y += mips_r4k.o mips_malta.o mips_mipssim.o mips_ar71xx.o ath_apbuart.o mips_broadcom.o ath_nand.o
obj-y += addr.o mips_int.o
obj-$(CONFIG_JAZZ) += mips_jazz.o
obj-$(CONFIG_FULONG) += mips_fulong2e.o
obj-y += gt64xxx_pci.o
obj-$(CONFIG_MIPS_CPS) += cps.o
obj-$(CONFIG_MIPS_BOSTON) += boston.o
